### PR TITLE
Normalize road layer kind values

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/tilezen/vector-datasource/issues/843

@nvkelso, @zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Does this need doc updates for the changed values?

**Comment by rmarianski** [comment]
I realized that I had implemented it incorrectly by updating the `kind` instead of the `aerialway` subkind. I fixed that in 8336b70. I also updated the docs to reflect the new possible values.

**Comment by zerebubuth** [comment]
I can't seem to comment on it directly, since it's outside the range of the diff, but `drive-through` needs an update on [line 886 of `layers.md`](https://github.com/tilezen/vector-datasource/pull/881/files#diff-606a00db54cec09bedc8a0a9e6e26a15R886).

**Comment by rmarianski** [comment]
Good catch. Updated in dc52c0f.

**Comment by zerebubuth** [comment]
Looks good  :+1:

**Pull request merged**
