### PR TITLE
Kkowalsky/docs update

### PR DESCRIPTION
**Pull request by kkowalsky**
This is just to update the 'Display Tiles' page with all six house styles and a new picture. I edited the code banks so they don't break my markdown in my editor.

### CODE REVIEW

**Comment by kkowalsky** [comment]
looking into why the builds failed...

**Comment by kkowalsky** [comment]
looks like 'integration-test/291-483-suppress-historical-closed.py', 'integration-test/857-move_barriers_to_landuse.py' both had exception errors in 'setup_and_run_tests.sh'

**Comment by nvkelso** [comment]
The PNG was a couple MB but is displayed small on the page, I compressed it to a GIF using PS. See https://github.com/tilezen/vector-datasource/pull/1114/commits/f07515d4e38a044873b573270bcb45fa5aada81b.

Now that we have product pages for each map style, we should direct people to mapzen.com instead of Github.io for these. See https://github.com/tilezen/vector-datasource/pull/1114/commits/f07515d4e38a044873b573270bcb45fa5aada81b.

**Comment by kkowalsky** [comment]
thanks for catching that @nvkelso!

**Comment by nvkelso** [comment]
@kkowalsky Merge against master and the test failures will be history.

**Comment by kkowalsky** [comment]
thanks for the fix @zerebubuth!

**Comment by nvkelso** [comment]
LGTM, thanks!

**Pull request merged**
