### PR TITLE
fix accidental test pass

### PR DESCRIPTION
**Pull request by matkoniecz**
- [x] Update tests
- [x] ~~Update data migrations (not necessary)~~
- [x] Update docs (not necessary)

I discovered bug in tests. For some unclear reason tests were still passing.

### CODE REVIEW

**Comment by matkoniecz** [comment]
(note I created #1339 to track problem listed below)

Now I am confused even more. Before I was not looking at test results (with "All checks have passed" and CircleCI website is quite laggy).

But now, after test that really should fail passed I looked at log and I see

> Exception: Tile u'http://localhost:46680/roads/11/1091/673.json': Did not find feature including properties {'kind_detail': 'track', 'id': 58691615, 'surface': 'concrete_lanes'} (because layer 'roads' was empty)

So, why github marks tests as passing?

**Comment by nvkelso** [comment]
Hmm. Github is showing success because CircleCI is showing success. 

But when I show details I see the following. @rmarianski can you take a look, please?

```
[ 175/175] PASS: 'integration-test/993-remove-props-road-merge.py'
FAILED 2 TESTS. For more information, see 'test.log'
+ success=1
+ [[ 1 -eq 0 ]]
+ cat test.log
[  23/175] FAIL: 'integration-test/1252-roads-surface.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 448, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/1252-roads-surface.py", line 40, in <module>
    { 'id': 58691615, 'kind_detail': 'track', 'surface': 'concrete_lanes'})
  File "./scripts/../integration-test.py", line 305, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 226, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 299, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile u'http://localhost:46680/roads/11/1091/673.json': Did not find feature including properties {'kind_detail': 'track', 'id': 58691615, 'surface': 'concrete_lanes'} (because layer 'roads' was empty)


[ 144/175] FAIL: 'integration-test/834-park-building.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 448, in __call__
    runpy.run_path(f, init_globals=dict(test=self.test_api))
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/834-park-building.py", line 11, in <module>
    { 'id': 239782410, 'kind': 'park' })
  File "./scripts/../integration-test.py", line 305, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 226, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 305, in assert_has_feature
    % (properties, closest['properties'], misses)
Exception: Tile u'http://localhost:46680/landuse/16/10493/22885.json': Did not find feature including properties {'kind': 'park', 'id': 239782410}. The closest match was {u'kind': u'bridge', u'sort_rank': 229, u'source': u'openstreetmap.org', u'min_zoom': 16.0, u'tier': 4, u'id': 239782410}: missed {'kind': "'bridge' != 'park'"}.
```

**Comment by rmarianski** [comment]
Trying a fix for the tests erroneously passing in https://github.com/tilezen/vector-datasource/pull/1341

**Comment by matkoniecz** [comment]
replaced by #1345

**Pull request closed without merging**
