### PR TITLE
Capture all test coordinates with -printcoords

### PR DESCRIPTION
**Pull request by rmarianski**
The biggest change here is to namespace all the test assertion functions using `test`. This is to emphasize that all assertions should be done this way.

### CODE REVIEW

**Comment by iandees** [comment]
Any reason we don't use the existing `unittest` framework?

**Comment by rmarianski** [comment]
> Any reason we don't use the existing unittest framework?

IIRC the idea was to create higher level tests that were easier to write than traditional unit tests. @zerebubuth can correct me if I'm wrong here.

**Comment by zerebubuth** [comment]
> IIRC the idea was to create higher level tests that were easier to write than traditional unit tests. 

The [original tests](https://github.com/tilezen/vector-datasource/commit/a431ccec498c58d30d88eee1e18ee69b9a7fdd1e) had to be run against a server, and didn't state their dependencies, which meant they needed a lot of setup and were unlike unit tests. I think, when I wrote them, I didn't use `unittest` because I was thinking of them as "release tests" or "acceptance tests". I guess that's why @rob moved them to be `integration-tests` when he wrote some actual unit tests :smile:

At some point, we added the ability for the code to read its own source to set up the database to run against. It's still not very "unit-y", though, as data from independent tests can interfere with each other because we don't set up the database anew for each test with only the dependencies it needs. Also, changes to the upstream data can make the tests fail.

However, we've been moving closer and closer to having self-contained unit tests. And we might finally get there with `@` annotations for the database contents that the test depends on. Those can be loaded up in a per-test setup and reset in a teardown so that the tests can't interfere with each other and the test result is only a function of the code and fixture, not the wider world.

At that point, it might be worth seeing if using `unittest` has any advantages over the way it is at the moment.

**Comment by iandees** [comment]
Sounds good. We might consider switching to use the `unittest` library at some point simply because it provides a useful framework with a lot of pre-built assertions. Tests don't necessarily have to be "capital-U" unit tests to use the `unittest` Python library.

**Pull request merged**
