### PR TITLE
Olga/742 predictable layers pois

### PR DESCRIPTION
**Pull request by okavvada**
Connects to #742.

- [x] Update tests
- [x] Update data migrations
- [x] Update docs

Ready for review, @nvkelso , @rmarianski , @zerebubuth

### CODE REVIEW

**Comment by zerebubuth** [comment]
Code changes look good!

The original issue talks about moving label positions to the `pois` layer, but nothing was taken out of the `landuse` layer YAML. I think we are making a lot of those label positions from the polygons in the post-process - do we also need to remove (or not generate) those label positions? Could you add a test to make sure that these aren't now in both layers, please?

**Comment by nvkelso** [comment]
@zerebubuth Good catch! 

My intent was to stop generating label positions in the **landuse** layer if the "label" was already in the **pois** layer (keep the landuse polygons, ditch the label placement). Is that already configured or does new logic need to be added (and where)?

There are still a few dozen landuse kinds that aren't in pois, those should get label placements but only starting at maybe zoom 13?

**Comment by zerebubuth** [comment]
I think it _should_ already have the logic to [set the landuse name to NULL if the feature is a POI](https://github.com/tilezen/vector-datasource/blob/dec70254a1c26a0fb9daa32758634be46e5bab29/queries/landuse.jinja2#L14), but it's pretty complicated and I'm not totally sure I understand it. Just to be on the safe side, seems worth adding some tests to assert that there are no matching features (with `label_placement:yes` - or is it `true` now?) in the `landuse` layer.

**Comment by okavvada** [comment]
@zerebubuth , I added the tests for label placement. Can you please check to make sure this is what you were thinking of?

**Comment by zerebubuth** [comment]
Thanks! That looks great! :+1:

**Comment by nvkelso** [comment]
@okavvada the PR looks good now, but let's still test on my local dev config before merging – this way we can see the impact on overall map balance first.

**Comment by okavvada** [comment]
okay @nvkelso

**Comment by okavvada** [comment]
Updated all the min_zoom levels we talked about with @nvkelso. Let me know if its ready to merge

**Pull request merged**
