### PR TITLE
Olga/951 remove place sea

### PR DESCRIPTION
**Pull request by okavvada**
Connects to #951.
- [x] Update tests
- [ ] Update data migrations
- [ ] Update docs

Ready for review @rmarianski , @zerebubuth , @nvkelso

### CODE REVIEW

**Comment by okavvada** [comment]
The issue is that although we are correctly dropping the sea polygon so it does not overlap the islands, we are not generating sea labels. This is true for prod as well.

**Comment by zerebubuth** [comment]
The label will be placed at a point within the polygon which we calculate in Python (although @rmarianski is currently moving some of that logic to the database in #963), and the same point can be found by running:

```sql
select osm_id, st_astext(st_transform(st_pointonsurface(way), 4326))
from planet_osm_polygon where osm_id = -4594226;
```

I've updated the test to use that point, and it passes on my computer. We'll have to wait and see if CircleCI agrees!

The migration shouldn't be needed, as the changes don't alter `mz_water_min_zoom`. When processing gets to the post-process steps from `queries.yaml`, the database has already done all its work.

**Comment by okavvada** [comment]
Thank you @zerebubuth for the help! I also deleted the migration as you were right, it was not needed.

**Comment by zerebubuth** [comment]
:+1: looks great!

**Comment by rmarianski** [comment]
Yea, the migration would only have been needed if the rule was removed in the yaml file.

:+1:

**Pull request merged**
