### PR TITLE
Add turning circles and turning loops to pois.yaml

### PR DESCRIPTION
**Pull request by westnordost**
Implements #1695

- [x] Update tests
- [x] Update docs

### CODE REVIEW

**Comment by nvkelso** [comment]
Nice! Don't need to do migrations anymore. See some of the recent PRs for generative test, or use the older format which is still supported (eg with an OSM id).

**Comment by westnordost** [comment]
Not sure what tests I would need to update.

**Comment by nvkelso** [comment]
You'll need to add a test. Generally we name the test file after the issue number and a descriptive string and place into the **integration-test/** dir (like `1695-turning-circles-turning-loops.py`): 

- https://github.com/tilezen/vector-datasource/blob/master/integration-test/1186-the-pois-with-no-name.py

Then you'd have something like, but modify so it covers both new kinds, and make sure that's the right coordinate for the zoom at lat/lng position as I hacked it together for you.

```
# -*- encoding: utf-8 -*-
from shapely.wkt import loads as wkt_loads
import dsl
from . import FixtureTest


# test turning circles and ...
class TurningCirlce(FixtureTest):

    def turning_circle(self):
        # comment
        self.generate_fixtures(dsl.way(1589837084, wkt_loads('POINT (-104.819282920265 39.61691951649848)'), {u'source': u'openstreetmap.org', u'highway': u'turning_circle'}))  # noqa

        self.assert_has_feature(
            16, 10461, 25315, 'pois',
            {'id': 1589837084})
```

**Comment by westnordost** [comment]
I do have a problem with this test setup, it seems to test much more than it should:
- It appears as if an actual OSM element is tested here, but I think this is not the case. (Still I entered a "real" one now, inclusive the tile numbers, meh)
- both the position and the tile numbers are irrelevant for the test and just adds noise + difficulty to implement (the implementer needs to find out in which tile number a given position is)

Ideally, I would want to do something like this:
```python
    def turning_circle(self):
        self.assert_convert_tags_at_zoom_level(
                16,
                {'highway': 'turning_circle'},
                {'kind': 'turning_circle'}
        )
```

**Comment by nvkelso** [comment]
I agree that the XY part of the ZXY coordinate shouldn't need to be manually noted by default... but we've run into cases in the past where it's important to specify the exact tile, especially for non-point features. In any case the layer also has to be specified because some features show up in 2 layers not just one.

**Comment by westnordost** [comment]
Sure, correct assignments of geometry to tiles should also have its test, but I'd say it should be a designated one. But anyway, that was only a side-note as a suggestion for improvement.
Regarding this PR, is there anything left to do?

**Comment by nvkelso** [comment]
@westnordost Circle says something is busted in the checks, looks like it's all line length and whitespace issues:

```
#!/bin/bash -eo pipefail
. ~/env/bin/activate
find . -not -path '*/.eggs/*' -not -path '*/data/*' -name '*.py' | xargs flake8
./integration-test/1695-turning-circles-turning-loops.py:10:80: E501 line too long (144 > 79 characters)
./integration-test/1695-turning-circles-turning-loops.py:15:1: W293 blank line contains whitespace
./integration-test/1695-turning-circles-turning-loops.py:17:80: E501 line too long (140 > 79 characters)
Exited with code 123
```

Please clean those up and then if Circle passes we should be all good to go.

**Comment by westnordost** [comment]
I can do that, though you should know that I copied the style as I saw it in other tests.

**Pull request merged**
