### PR TITLE
Estimate population for null pop OSM places

### PR DESCRIPTION
**Pull request by nvkelso**
For #1992
Break out filters in landuse.yaml for different localities by whether they have a population listed or not.  If they don't, make the min_zoom higher and estimate the population.  
- [X] Update tests

### CODE REVIEW

**Comment by nvkelso** [comment]
Over to @travisgrigsby to take this over the finish line.

**Comment by nvkelso** [comment]
Please also update the newly failing tests:

- 982-remove-unstyled-localities
- 988-add-population-to-collision-rank

**Review by nvkelso — COMMENTED** [review]
The logic and new tests look good.

Please fix the other 2 related tests and then ready to merge.

**Review by travisgrigsby — APPROVED** [review]
We still need to clean up the unstyledLocalities tests

**Comment by nvkelso** [comment]
Closed in favor of https://github.com/tilezen/vector-datasource/pull/2013.

**Pull request closed without merging**
