### PR TITLE
Cleanup poi kind filters

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/tilezen/vector-datasource/issues/844

@nvkelso, @zerebubuth could you review please?

### CODE REVIEW

**Comment by nvkelso** [comment]
👍

**Comment by zerebubuth** [comment]
There are a couple of nodes tagged `aeroway=gate, barrier=gate` ([here](http://www.openstreetmap.org/node/2618197593) and [here](http://www.openstreetmap.org/node/877193500)). At the moment, the check for `barrier=gate` comes before `aeroway=gate`, so these will get `kind:gate` (although with an additional `aeroway:` property).

It seems to me that `aeroway=gate` is more "specific"... Should we put that above the `barrier=gate` check and remove the extra `aeroway:` property from the `barrier=gate` check? (I'm not seeing anything that's `barrier=gate` but `aeroway != gate`)

**Comment by zerebubuth** [comment]
Upon closer inspection of the examples - neither are traditional passenger en-planing points. One is a [dock-side gate for Victoria Seaplane Terminal](http://www.openstreetmap.org/node/2618197593) and the other seems to be a [gate on an access taxiway](http://www.openstreetmap.org/node/877193500) to a DLR research base from a ["special" airport](http://www.edmo-airport.de/en) which doesn't seem to do commercial flights.

So perhaps it's better to give both `kind:gate`, although I still think it might be worth taking off the additional `aeroway:` property.

**Comment by rmarianski** [comment]
Good points. I added the first example as a test case, and removed the `aeroway` tag in 0488d5f.

**Comment by zerebubuth** [comment]
:+1: looks good

**Comment by nvkelso** [comment]
👍

**Pull request merged**
