### PR TITLE
Spanish road shields.

### PR DESCRIPTION
**Pull request by zerebubuth**
It looks like Spanish road refs can be on one of four levels:

* National; `A` and `N` roads,
* Autonomous Community,
* Province,
* City.

I've tried to organise these as the following networks:

* `ES:A-road` & `ES:N-road`,
* `ES:autonoma:{iso_code}`,
* `ES:province:{iso_code}`,
* `ES:city:{city_name}`.

I'm not entirely sure how these are displayed in shields. The examples I found for the `A` roads were signed as `A-#`, see [road sign](http://storage2.openstreetcam.org/files/photo/2017/1/20/lth/31367_c1d14_5881663705efe.jpg) on [OpenStreetCam](http://openstreetcam.org/details/31367/7327/track-info). Toll roads are signed `AP-#`, see [road sign](http://storage2.openstreetcam.org/files/photo/2016/8/21/lth/12936_47b84_57b9ab04859a9.jpg) on [OpenStreetCam](http://openstreetcam.org/details/12936/206/track-info). `N` roads seem to be signed `N-#`, see [road sign](http://storage2.openstreetcam.org/files/photo/2016/8/21/lth/13054_7df7d_57ba1f9801a57.jpg) on [OpenStreetCam](http://openstreetcam.org/details/13054/47/track-info).

There are some refs which will require spatial lookups to fix. I've left those for ☂.

Connects to #1521. Connects to #1491.

### CODE REVIEW

**Comment by nvkelso** [comment]
For reference:

- https://commons.wikimedia.org/wiki/Road_signs_of_Spain
     https://es.wikipedia.org/wiki/Anexo:Se%C3%B1ales_de_tr%C3%A1fico_de_indicaci%C3%B3n_de_Espa%C3%B1a
    Señales de Identificación de Carreteras
    image
- A, AP are the same blue; `Autopista o Autovía` (federal Highway and Highway in autonomous area?) and `Autopista de Peaje` (Tollway)
    - Identifies a highway or highway. When this is of regional scope, in addition to the letter A and after the corresponding number or on top of the signal with a complementary panel, the acronym of identification of the Autonomous Community can be included.
    - No highway that does not have highway or highway characteristics can be identified with the letter A.
    - When the highway or highway is a round or bypass the letter A may be replaced by the letters indicating the city, in accordance with the code established for this purpose by the Ministries of Development and Interior.
- N red, `Carretera de la red general del Estado`
    - Highway of the general network of the State 
    - Identifies a highway of the general network of the State , that is not freeway or highway.
- CL orange, `Carretera autonómica de primer nivel`
    - First level autonomous road 
    - Identifies a first level road, which is not a highway or dual carriageway, of the autonomous community network to which the initials of identification correspond.
- A green, `Carretera autonómica de segundo nivel`
    - Second level autonomous highway 
    - Identifies a second level road, which is not a highway or dual carriageway, of the autonomous community network to which the initials of identification correspond.
- CA yellow `Carretera autonómica de tercer nivel`
    - Third level autonomous road 
    - Identifies a third level road, other than motorway or dual carriageway, of the autonomous community network to which the identification acronym corresponds.

**Comment by nvkelso** [comment]
Hmm, I don't see a lot of rhyme or reason behind the road shield color and the province for the `orange`, `green`, and `yellow` shields.

- https://es.wikipedia.org/wiki/Anexo:Autopistas_y_autov%C3%ADas_de_Espa%C3%B1a

This looks helpful, an OSM tag just for Spain:

- https://wiki.openstreetmap.org/wiki/Key:ref:colour

image

Based on that I think we should default roads in Spain based on the above table, unless they have a `ref:colour` override, and drop a lot of the Autonomous Community and Province information (like we dropped that in France), but instead use it to inform the colors with the 3rd network component indicating the "class" or "colour"?

- `ES:A-road` (no change)
- `ES:N-road` (no change)
- `ES:autonoma:{class}` - a change from ISO code based on:
    - `ES:autonoma:primary` shown in orange
    - `ES:autonoma:secondary` shown in green 
    - `ES:autonoma:tertiary` shown in yellow 
- `ES:province:{class}` - a change from ISO code based on:
    - `ES:province:secondary` shown in green
    - `ES:province:tertiary` shown in yellow 
- `ES:city:{class}`
    - `ES:city:primary` shown shown in blue for anything motorway, trunk, primary?
    - `ES:city:secondary` shown in ??
    - `ES:city:tertiary` shown in yellow 
- Else use https://wiki.openstreetmap.org/wiki/Key:ref:colour?

**Comment by zerebubuth** [comment]
I've been trying to rationalise this, but I keep running into lots of inconsistencies. For example, a small sample of funkiness:

* [`ZA-20`](https://es.wikipedia.org/wiki/ZA-20) / [`ZA-13`](https://es.wikipedia.org/wiki/ZA-13) ([OSM way](https://www.openstreetmap.org/way/46699451), [relation](https://www.openstreetmap.org/relation/4080339)) is [clearly signed](http://storage8.openstreetcam.org/files/photo/2018/6/4/lth/1223259_4b272_33.jpg) as `N-630` [even on the mile markers](http://storage8.openstreetcam.org/files/photo/2018/6/4/lth/1223259_26bf7_21.jpg).
* Here's [`Z-30`](https://es.wikipedia.org/wiki/Z-30), which has a blue shield on one wiki page, but a [red one on this one](https://es.wikipedia.org/wiki/Anexo:Autopistas_y_autov%C3%ADas_de_Espa%C3%B1a). The [sign appears to be blue on the ground](http://storage2.openstreetcam.org/files/photo/2016/10/6/lth/24375_ff07a_57f65486cb133.jpg), and the [way](https://www.openstreetmap.org/way/23076446) is mostly tagged `highway=trunk`. So maybe `highway=trunk` implies A-road, or national road?
* But here's [`VG-1.3`](https://es.wikipedia.org/wiki/VG-1.3), which gets a [green "secondary" shield](https://www.mapillary.com/app/?lat=43.36214105&lng=-8.30664343&z=17&pKey=cib9tsCxPh_onH7KraR8IA&focus=photo&x=0.58498789300431&y=0.5939979008841582&zoom=0.6424242424242423), but is also [a `highway=trunk` road](https://www.openstreetmap.org/way/172717324).

:man_shrugging: 

I'm not sure the data is good enough to reliably identify more than just `A-road` and `N-road` networks :frowning_face: 

What do you think?

**Comment by nvkelso** [comment]
Let's just do the national roads for now and do the others as followup for a rainy day.

**Comment by zerebubuth** [comment]
In 1fb902d,

* A-roads map to `ES:A-road`,
* N-roads map to `ES:N-road`,
* Other roads are mapped to one of `ES:autonoma`, `ES:province` or `ES:city`, if we can tell which they come from.

On the autonoma, provincial and city roads I've kept the prefix in `shield_text`, since we don't keep that information in the `network` any more.

See #1531 for the follow-up.

How does it look?

**Pull request merged**
