### PR TITLE
Update test, original node deleted

### PR DESCRIPTION
**Pull request by rmarianski**
@zerebubuth, @iandees, @nvkelso could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Looks like `integration-test/647-cycle-route.py` is also failing because

```
Exception: Tile 'http://localhost:57946/roads/16/10487/25327.json': Did not find feature including properties {'kind': 'major_road', 'bicycle_network': 'lcn', 'cycleway': 'lane'}. The closest match was {u'cycleway_right': u'lane', u'name': u'The Embarcadero', u'sort_rank': 380, u'kind_detail': u'primary', u'is_bicycle_related': True, u'kind': u'major_road', u'bicycle_network': u'lcn', u'source': u'openstreetmap.org', u'min_zoom': 8.0, u'oneway': u'yes', u'sidewalk': u'separate', u'id': 88466052}: missed {'cycleway': "None != 'lane'"}.
```

It looks like it's picking up [this way](http://www.openstreetmap.org/way/88466052) instead of [the way it's supposed to](http://www.openstreetmap.org/way/24335490) because the latter was recently edited to have `cycleway:right=lane` rather than `cycleway=lane`. Unless there was a specific reason why we were testing one rather than the other, it's probably good enough just to change that to `cycleway_right`. Is it worth adding an `id` as well, so that it only tries to match the intended element?

**Comment by zerebubuth** [comment]
Got some more fixes in e371f9d, which passes locally for me. Fingers crossed that Circle feels the same way!

**Comment by rmarianski** [comment]
And it does! Ok to merge?

**Comment by nvkelso** [comment]
Woot! Merging.

**Pull request merged**
