### PR TITLE
add initial changelog for v1.0.0-pre1

### PR DESCRIPTION
**Pull request by nvkelso**
Another set of release notes, another Markdown style.

### CODE REVIEW

**Comment by nvkelso** [comment]
The **requires** is definitely not correct! (But waiting for updated tags or SHAs on those.)

**Comment by nvkelso** [comment]
Added commit to:

* update URL section
* remove TileStashe requirement, and note removal of same in Internal Changes section
* add buroughs from WOF
* reformat (#issue_number) on end of each list item for see more details links

**Comment by nvkelso** [comment]
@rmarianski what should I mention in the **requires** section for tileserver and tilequeue?

Other than that I think this is ready to be merged?

**Comment by rmarianski** [comment]
We'll need to make new releases for tileserver and tilequeue as well and point to those.

**Comment by nvkelso** [comment]
@rmarianski what SHAs did you use for the v1.0.0-pre1 release on dev? Should we cut new dev releases or point at the SHA?

**Comment by rmarianski** [comment]
Just pointed to the master branches. We should just cut new releases of those repos.

**Comment by rmarianski** [comment]
@nvkelso I put up some prs with changelogs and version bumps for tilequeue and tileserver. If those look good to you, I'll go ahead and make the tags.

**Pull request merged**
