### PR TITLE
Use the NE min zoom to cull places at low zooms.

### PR DESCRIPTION
**Pull request by zerebubuth**
We were already using the NE min zoom as the min_zoom property, but had failed to actually act on that by removing items outside of the zoom range.

Overall file size reduction (NOTE: most of the very low zoom labels come from the `earth` layer - things like continent labels):

Tile | Previous places size (bytes) | New places layer size (bytes) | Percentage improvement
-- | -- | -- | --
0/0/0 | 518,111 | 0 | 100%
1/0/0 | 139,980 | 0 | 100%
1/0/1 | 42,043 | 0 | 100%
1/1/0 | 266,788 | 0 | 100%
1/1/1 | 83,228 | 0 | 100%
2/0/0 | - | - | -
2/0/1 | 33,015 | 14,536 | 56%
2/0/2 | 20,091 | 1,979 | 90%
2/0/3 | - | - | -
2/1/0 | 4,326 | 4,091 | 5%
2/1/1 | 178,337 | 44,582 | 75%
2/1/2 | 58,487 | 20,020 | 66%
2/1/3 | - | - | -
2/2/0 | 2,145 | 0 | 100%
2/2/1 | 410,712 | 110,756 | 73%
2/2/2 | 83,789 | 32,137 | 62%
2/2/3 | - | - | -
2/3/0 | 827 |   | 100%
2/3/1 | 155,139 | 44,066 | 72%
2/3/2 | 44,228 | 21,546 | 51%
2/3/3 | - | - | -

## Zoom 0

It's all continent and ocean labels, no places visible.

z0

## Zoom 1

It's all continent and ocean labels, no places visible.

z1

## Zoom 2

I was expecting _some_ places to be visible at this zoom level, as some are present in the tiles. Perhaps the label collision prevents any from appearing?

z2

## Zoom 3

Looks like a pretty good selection of capitals, major cities and country labels.

z3

## Zoom 4

Nice overview of US states and major cities. Do we have the same state data for Canada - given that we show the state borders, it might be nice to label them too? Perhaps a :umbrella: issue?

z4

### CODE REVIEW

**Comment by zerebubuth** [comment]
Connects to #1687.

Note that tile `2/2/1` is still pretty huge - 110,756 bytes. However most (69%) of this is properties, which will get better once we implement #1643.

**Comment by nvkelso** [comment]
Here's what I see in Natural Earth for these zooms:

screen shot 2018-10-25 at 09 54 31

screen shot 2018-10-25 at 09 54 47

screen shot 2018-10-25 at 09 55 01

screen shot 2018-10-25 at 09 55 35

**Comment by nvkelso** [comment]
Also, your zoom 2 looks pretty weird!?

**Comment by nvkelso** [comment]
The likely reason you're not seeing Canada region labels at zoom 3 is they are set to 3.5 and Tangram only does the evaluation at zoom 3 (and 3.5 !< 3 so it filters them out). Or your PR / existing code filters them.

**Comment by zerebubuth** [comment]
Yup, zoom 2 was messed up because I was using the Go version of `tapalcatl`, which doesn't understand the "max zoom packing" feature/hack that we added to `tapalcatl-py`. Moving to the latter, I now see:

z2-again

Which is has a bunch of cities on it. :tada: 

(Although no space for London? What's up with that? :scream_cat:)

**Pull request merged**
