### PR TITLE
Added local-branch deployment command to rebuild docs

### PR DESCRIPTION
**Pull request by migurski**
I am setting up some proactive connections from upstream documentation repos to the central Mapzen repository. This change will cause CircleCI to trigger rebuilds on that repository, after [merge of PR #233](https://github.com/mapzen/mapzen-docs-generator/pull/223).

- [x] Wait for tests to pass to verify that this works for this branch.
- [x] Reconfigure to run regardless of branch, or select a branch or release.

### CODE REVIEW

**Comment by migurski** [comment]
Also referenced from https://github.com/mapzen/mapzen-docs-generator/issues/224.

**Comment by migurski** [comment]
Talking with @nvkelso, we think that:

1. Nathaniel has added and will maintain [a branch in `mapzen/mapzen-docs-generator` called something like `tilezen-buildbot/tiles-prerelease-docs`](https://github.com/mapzen/mapzen-docs-generator/commits/tilezen-buildbot/tiles-prerelease-docs), and that's where he’ll keep a version pointing to `master` source URLs in the Makefile.
2. We'll have _two_ tickle rules in this repo:
    1. One for vectors `master` for the docs `nvkelso/vector-tiles-prerelease` branch above.
    2. Another for vectors [latest tagged release](https://developer.github.com/v3/repos/releases/#get-the-latest-release) for the docs `master` branch. @migurski will need to modify the docs Makefile in order to understand how to interpret "latest release". This will allow @kkowalsky to make edits to the vectors docs, tiles team will tag a new release, and those updates will automagically go live.

**Comment by migurski** [comment]
2.ii. is complete now, so I’ll just need to make the 2.i. changes here and in Joerd.

**Comment by kkowalsky** [comment]
LGTM, I'm comfortable merging once 2.i is complete.

**Comment by migurski** [comment]
Just set this up identically to https://github.com/tilezen/joerd/pull/114; should be ready to go when Circle comes back.

**Comment by migurski** [comment]
(2.i is complete)

**Comment by kkowalsky** [comment]
Great, merge when Circle is happy!

**Comment by nvkelso** [comment]
Merged against master to deal with the carousel fix.

**Comment by nvkelso** [comment]
(We're about to push v1.0.2 to prod, trying this path...)

**Comment by nvkelso** [comment]
Looks like someone [edited](https://www.openstreetmap.org/relation/6722301#map=19/38.90391/-77.08073) one of our data fixtures", likely moving the generated label position into a neighboring tile: 

```
[  26/154] FAIL: 'integration-test/399-add-island-labels.py'
Traceback (most recent call last):
  File "./scripts/../integration-test.py", line 519, in run_test
    'features_in_mvt_layer': features_in_mvt_layer,
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 240, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/circleci/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "integration-test/399-add-island-labels.py", line 41, in <module>
    { 'kind': 'archipelago', 'label_placement': True, 'min_zoom': 15, 'name': 'Three Sisters Islands' })
  File "./scripts/../integration-test.py", line 292, in assert_has_feature
    % (properties, closest['properties'], misses)
  File "/opt/circleci/python/2.7.10/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "./scripts/../integration-test.py", line 189, in features_in_tile_layer
    yield features
  File "./scripts/../integration-test.py", line 286, in assert_has_feature
    "%r (because layer %r was empty)" % (properties, layer)
Exception: Tile 'http://localhost:48283/earth/15/9367/12534.json': Did not find feature including properties {'label_placement': True, 'kind': 'archipelago', 'min_zoom': 15, 'name': 'Three Sisters Islands'} (because layer 'earth' was empty)
```

**Comment by nvkelso** [comment]
This test is working in prod (same tile coordinate), but prod is using older data than our Overpass instance at the moment (older than 2 days when the upstream OSM data edit was made). Merging anyhow.

**Pull request merged**
