### PR TITLE
Rename sort_key to sort_rank

### PR DESCRIPTION
**Pull request by iandees**
- [x] Update tests
- [ ] No data migrations needed
- [x] Update docs

Connected to #1048.

### CODE REVIEW

**Comment by iandees** [comment]
This looks OK to me. @rmarianski did I miss anything on this change?

**Comment by nvkelso** [comment]
Looks good to me.

**Comment by zerebubuth** [comment]
Wow, that's a lot of changes! Nice work :smile:

Should we also change:

```
queries.yaml:324:      cutting_attrs: { sort_key: 'sort_key', reverse: True }
queries.yaml:607:      cutting_attrs: { sort_key: 'sort_key', reverse: True }
```

to

```
queries.yaml:324:      cutting_attrs: { sort_key: 'sort_rank', reverse: True }
queries.yaml:607:      cutting_attrs: { sort_key: 'sort_rank', reverse: True }
```

?

This bit of code/config tries to ensure that when we "overlap" buildings with landuse (the first line) or "cut" roads against landuse (the second line) then we do it in order of decreasing `sort_rank` so that landuse polygons "on top" are the first to be considered. The effect is to assign a `landuse_kind` to the road or building which matches the background landuse polygon, for example so that roads through a national park can have a slightly green casing.

**Comment by rmarianski** [comment]
Only thing I noticed is what @zerebubuth mentioned. Otherwise LGTM.

**Comment by zerebubuth** [comment]
Great! Looks good to me :+1:

**Pull request merged**
