### PR TITLE
Olga/875 camp grounds sort key

### PR DESCRIPTION
**Pull request by okavvada**
- [x] Update tests
- [ ] Update data migrations
- [ ] Update docs

Ready for review, @zerebubuth , @rmarianski (hope I did it right this time) , @nvkelso

### CODE REVIEW

**Comment by rmarianski** [comment]
Is it ok for `camp_site` and `maze` to have the same sort order?

**Comment by nvkelso** [comment]
Correct, `maze` and all other "higher" kinds need to increment their current value by +1 (e.g.: `93` instead of `92`)

**Comment by okavvada** [comment]
Updated the sort_keys and updated test 663 with the correct sort_keys

**Comment by rmarianski** [comment]
:+1:

**Comment by nvkelso** [comment]
💯

**Pull request merged**
