### PR TITLE
Allow null refs in shield text. Attempt to sanitize shield text.

### PR DESCRIPTION
**Pull request by zerebubuth**
Connects to #192.

@nvkelso could you review, please?

### CODE REVIEW

**Comment by nvkelso** [comment]
👍

**Comment by nvkelso** [comment]
@rmarianski Can you also take a look and merge if all is good?

**Comment by rmarianski** [comment]
:+1:

**Comment by nvkelso** [comment]
Regarding comment in in https://github.com/tilezen/vector-datasource/issues/192#issuecomment-245509369: 

Is this stripping off all leading `A ` characters from strings like `A 100` resulting in just `100` in the shield text instead of `A100`?

**Comment by nvkelso** [comment]
@zerebubuth for above comment.

**Comment by nvkelso** [comment]
Spot checked most of these, looking good!

**Pull request merged**
