### PR TITLE
Clip buildings to tiles.

### LINKED ISSUE #1142: Clip buildings
Buildings are clipped at [3x3 tile boundaries](https://github.com/tilezen/vector-datasource/blob/1ab3ebadcf4c8fa5eab3ef55d2d0e6ed6cb003a2/queries.yaml#L107), and has its own side effects, alpha issues? cc @meetar @bcamper 

We should try clipping buildings like other features on dev to see if that introduces any artifacts.

### PR DESCRIPTION
**Pull request by zerebubuth**
Looks like this was done already as part of #1352, so this PR just updates the test to have the behaviour that we want; that all building geometry is within the tile bounds.

Fixes #1142.

### CODE REVIEW

**Comment by nvkelso** [comment]
This is not obvious, but if you follow all the issue references, we're hoping the building clip solves the landuse_kind intercut problems in https://github.com/tilezen/vector-datasource/issues/1226. Can you add tests in this PR to prove that's true, please?

**Comment by zerebubuth** [comment]
This won't solve all the `landuse_kind` intercut problems, but it might make it better. I'll add some examples.

Just to be clear: We'll get different kinds of problems instead when buildings cross tile boundaries and one half gets assigned a different `landuse_kind` than the other. E.g:

image

**Comment by nvkelso** [comment]
Well, sorry to be the bearer of bad news but now https://github.com/tilezen/vector-datasource/issues/1226 is assigned to you, too ;) 

Thanks for the illustration. I agree it's a related but different issue than this one.

**Comment by zerebubuth** [comment]
@nvkelso how do those new tests look?

**Comment by zerebubuth** [comment]
@nvkelso all good to merge?

**Comment by nvkelso** [comment]
Yes.

**Pull request merged**
